version: 2

references:
  container_config: &container_config
    docker:
      # Main Python container
      - image: circleci/python:3.6.2

jobs:
  build:
    <<: *container_config

    steps:
      - checkout
      - run:
          name: 'Setup virtual environment'
          command: |
            python3 -m venv ./virtualenvs/tap-zuora
            . ./virtualenvs/tap-zuora/bin/activate
            pip install --upgrade pip
            pip install -e .[test]

      - run:
          name: 'Pylinting'
          command: |
            . ./virtualenvs/tap-zuora/bin/activate
            pylint --rcfile .pylintrc tap_zuora

workflows:
  version: 2
  build:
    jobs:
      - build
